Use service server IPs from Sidecar
Nitro/traefik pull request #11
Opened 2017-05-12 18:36 UTC by mihaitodor

This is a follow-up to the conversation from [here](https://github.com/Nitro/traefik/pull/7#discussion_r113909627).

We want to fetch the IP addresses from Sidecar, if possible.

TODO:
- [ ] rebase this once #8 goes in.

2017-05-19 14:31 UTC, mihaitodor commented
@relistan @bparli Please have a look and let me know what you think.

2017-05-19 18:57 UTC, bparli commented
> do we want to not add the server at all if the hostname can't be resolved to an IP or should we just let Traefik deal with that?

I'd gone back and forth on this before, but lean towards not adding it now.  I think you'd argued this previously too @mihaitodor; if we can't resolve the address at this stage, the rest of the program likely won't be able to either.

2017-05-22 10:52 UTC, mihaitodor commented
OK @bparli, I updated the code.

@relistan May I go ahead and merge this changeset?

2017-05-23 09:09 UTC, relistan requested changes
Code looks good, some comments below.

2017-05-23 09:09 UTC, relistan commented on provider/sidecar.go
> +					if len(svc.Ports) > 1 {
Let's just make them consistent and always use the port.

2017-05-23 09:09 UTC, relistan commented on provider/sidecar.go
> +					if host == "" {
I don't do this in Sidecar and should, but let's be careful here to make sure we got a properly formed IP address by doing an [`net.ParseIP`](https://golang.org/pkg/net/#ParseIP) here to make sure it's a valid IP as well.

2017-05-23 09:09 UTC, relistan commented on provider/sidecar_test.go
> +						service.Port{
`gofmt -s` on this file and it will probably remove these inner `service.Port` names.

2017-05-23 09:09 UTC, relistan commented on provider/sidecar_test.go
This seems like way too much stuff to be checking in a single test. The comments explaining all the checks are the giveaway. Even if you have to repeat the same loading of the data multiple times in separate tests, this should be broken into tests that are validating the same functionality. Just share the setup between the `Convey` blocks and give the `So` clauses a wrapper that explains what they're doing.

2017-05-23 10:51 UTC, mihaitodor commented on provider/sidecar_test.go
> +						service.Port{
Nice catch @relistan! So, it turns out that the standard `goimports` [doesn't support](https://github.com/golang/go/issues/8759) the `-s` flag that `gofmt` provides. I ended up installing [this](https://github.com/jzelinskie/tools) 3rd party `goimports` to have this flag and keep using the `goimports` hook on save.

2017-05-23 11:08 UTC, mihaitodor commented on provider/sidecar_test.go
Good point! I'm starting to like goconvey :)

2017-05-23 11:56 UTC, mihaitodor commented
@relistan I think I covered everything. Please let me know if it's good to go now.

2017-05-23 12:22 UTC, relistan commented on provider/sidecar_test.go
> +						service.Port{
Yep, that's one annoyance of goimports. 💯 I'll take a look at the fork.

2017-05-23 12:24 UTC, relistan commented
:shipit: !

2017-05-23 12:25 UTC, merged